<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="James Packman">
<meta name="dcterms.date" content="2025-04-17">

<title>Exploratory Factor Analysis – Packman_504_Blog</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Packman_504_Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Exploratory Factor Analysis</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">news</div>
                <div class="quarto-category">code</div>
                <div class="quarto-category">analysis</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>James Packman </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">April 17, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p>Let’s get started with exploratory factor analysis (EFA). This is a method for doing factor analysis when you don’t have an explicit hypothesis about the underlying factor structure (i.e., which variables go with which factors).</p>
<section id="data-overview" class="level1">
<h1>Data Overview</h1>
<p>First, let’s discuss the example data set we’ll be using. These data are taken from a subset of survey data collected by the ADL and National Opinion Research Center (NORC) on people’s attitudes about Jewish people in the United States.</p>
<p>Specifically, the data we’ll be using contain participants’ responses to questions assessing their beliefs in stereotypes about Jewish people in the U.S. These items comprise the Scale of Antisemitic Stereotypes, a.k.a. the “SASS” (Packman et al., under review; will be linked here when/if published). Check out the methodological appendix here for information about the survey and data collection: <a href="https://www.adl.org/resources/report/antisemitic-attitudes-america-topline-findings" class="uri">https://www.adl.org/resources/report/antisemitic-attitudes-america-topline-findings</a></p>
<p>The scale, as it appeared in the survey, appeared like this:</p>
<p>Instructions: “Below are a number of statements with which you will agree or disagree. There are absolutely no right or wrong answers. Use the specified scale to indicate the number that best matches your response to each statement.”</p>
<ol type="1">
<li><p>Jewish people are often very rude.</p></li>
<li><p>Jewish people tend to complain a lot.</p></li>
<li><p>All things considered, Jewish people are untrustworthy.</p></li>
<li><p>Jewish people can be sneaky.</p></li>
<li><p>When they feel slighted, Jewish people will be vengeful.</p></li>
<li><p>Jewish people tend to be very good with money.</p></li>
<li><p>Jewish people tend to influence the media.</p></li>
<li><p>When it comes to education, Jewish people tend to be overachievers.</p></li>
<li><p>On the whole, Jewish people are loyal to Israel.</p></li>
</ol>
<p>Participants respond to each stereotype statement on a Likert scale from 1 (“strongly disagree”) to 6 (“Strongly agree”). An even-numbered Likert scale prevents participants from hiding behind neutral answers.</p>
<section id="data-import-cleaning" class="level2">
<h2 class="anchored" data-anchor-id="data-import-cleaning">Data Import &amp; Cleaning</h2>
<p>Let’s begin by loading the required packages.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Load Required Packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GPArotation)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nFactors)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Rmisc)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(coefficientalpha)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plyr)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mvnormtest)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(QuantPsyc)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ltm)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(easystats)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(parameters)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"papaja"</span>)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Rmisc)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(InteractionPoweR)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magick)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we’ll upload and clean the data (please reach out if, for some reason, you don’t have access to the data). Don’t worry about the data cleaning. It mostly involves list-wise deletion of NAs because factor analysis is really bad with missing data. The questions we’re interested in were only presented to N = 1960 out of 4176 participants, so we have a lot of blank space in the data set corresponding to participants we don’t need to assess. Note that we only remove these NAs for factor analyses; for other analyses, we use other methods.</p>
</section>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h2>
<p>Let’s briefly take a look at the data. We’ll calculate summary statistics and internal consistency.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary.data.frame</span>(SASSEFA) <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 0%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 6%">
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 16%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Jewish.people.are.often.very.rude</th>
<th style="text-align: left;">Jewish.people.tend.to.complain.a.lot</th>
<th style="text-align: left;">All.things.considered.Jewish.people.are.untrustworthy</th>
<th style="text-align: left;">Jewish.people.can.be.sneaky</th>
<th style="text-align: left;">When.they.feel.slighted.Jewish.people.will.be.vengeful</th>
<th style="text-align: left;">Jewish.people.tend.to.be.good.with.money</th>
<th style="text-align: left;">Jewish.people.tend.to.influence.the.media</th>
<th style="text-align: left;">When.it.comes.to.education.Jewish.people.tend.to.be.overachievers</th>
<th style="text-align: left;">On.the.whole.Jewish.people.are.loyal.to.Israel</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Min. :1.00</td>
<td style="text-align: left;">Min. :1.000</td>
<td style="text-align: left;">Min. :1.000</td>
<td style="text-align: left;">Min. :1.000</td>
<td style="text-align: left;">Min. :1.000</td>
<td style="text-align: left;">Min. :1.000</td>
<td style="text-align: left;">Min. :1.000</td>
<td style="text-align: left;">Min. :1.000</td>
<td style="text-align: left;">Min. :1.000</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">1st Qu.:4.00</td>
<td style="text-align: left;">1st Qu.:3.000</td>
<td style="text-align: left;">1st Qu.:4.000</td>
<td style="text-align: left;">1st Qu.:3.000</td>
<td style="text-align: left;">1st Qu.:3.000</td>
<td style="text-align: left;">1st Qu.:2.000</td>
<td style="text-align: left;">1st Qu.:3.000</td>
<td style="text-align: left;">1st Qu.:3.000</td>
<td style="text-align: left;">1st Qu.:2.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Median :4.00</td>
<td style="text-align: left;">Median :4.000</td>
<td style="text-align: left;">Median :5.000</td>
<td style="text-align: left;">Median :4.000</td>
<td style="text-align: left;">Median :4.000</td>
<td style="text-align: left;">Median :3.000</td>
<td style="text-align: left;">Median :4.000</td>
<td style="text-align: left;">Median :3.000</td>
<td style="text-align: left;">Median :3.000</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Mean :4.37</td>
<td style="text-align: left;">Mean :4.147</td>
<td style="text-align: left;">Mean :4.724</td>
<td style="text-align: left;">Mean :4.257</td>
<td style="text-align: left;">Mean :4.073</td>
<td style="text-align: left;">Mean :2.805</td>
<td style="text-align: left;">Mean :3.927</td>
<td style="text-align: left;">Mean :3.202</td>
<td style="text-align: left;">Mean :2.894</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">3rd Qu.:5.00</td>
<td style="text-align: left;">3rd Qu.:5.000</td>
<td style="text-align: left;">3rd Qu.:6.000</td>
<td style="text-align: left;">3rd Qu.:5.000</td>
<td style="text-align: left;">3rd Qu.:5.000</td>
<td style="text-align: left;">3rd Qu.:3.000</td>
<td style="text-align: left;">3rd Qu.:5.000</td>
<td style="text-align: left;">3rd Qu.:4.000</td>
<td style="text-align: left;">3rd Qu.:4.000</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Max. :6.00</td>
<td style="text-align: left;">Max. :6.000</td>
<td style="text-align: left;">Max. :6.000</td>
<td style="text-align: left;">Max. :6.000</td>
<td style="text-align: left;">Max. :6.000</td>
<td style="text-align: left;">Max. :6.000</td>
<td style="text-align: left;">Max. :6.000</td>
<td style="text-align: left;">Max. :6.000</td>
<td style="text-align: left;">Max. :6.000</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cronbach.alpha</span>(SASSEFA, <span class="at">CI =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Cronbach's alpha for the 'SASSEFA' data-set

Items: 9
Sample units: 1960
alpha: 0.832

Bootstrap 95% CI based on 1000 samples
 2.5% 97.5% 
0.817 0.845 </code></pre>
</div>
</div>
<p>Our Cronbach’s alpha is pretty high: 0.832, 95% C:I [0.817, 0.845]. But let’s make a nicer-looking table.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>(#tab:unnamed-chunk-4) Scale of Antisemitic Stereotypes Descriptive Statistics</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Questions</th>
<th style="text-align: left;">Mean</th>
<th style="text-align: left;">Median</th>
<th style="text-align: left;">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Jewish people are often very rude</td>
<td style="text-align: left;">4.37</td>
<td style="text-align: left;">4.00</td>
<td style="text-align: left;">1.08</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jewish people tend to complain a lot</td>
<td style="text-align: left;">4.15</td>
<td style="text-align: left;">4.00</td>
<td style="text-align: left;">1.14</td>
</tr>
<tr class="odd">
<td style="text-align: left;">All things considered, Jewish people are untrustworthy</td>
<td style="text-align: left;">4.72</td>
<td style="text-align: left;">5.00</td>
<td style="text-align: left;">1.08</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jewish people can be sneaky</td>
<td style="text-align: left;">4.26</td>
<td style="text-align: left;">4.00</td>
<td style="text-align: left;">1.17</td>
</tr>
<tr class="odd">
<td style="text-align: left;">When they feel slighted, Jewish people will be vengeful</td>
<td style="text-align: left;">4.07</td>
<td style="text-align: left;">4.00</td>
<td style="text-align: left;">1.15</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jewish people tend to influence the media</td>
<td style="text-align: left;">3.93</td>
<td style="text-align: left;">4.00</td>
<td style="text-align: left;">1.16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jewish people tend to be good with money</td>
<td style="text-align: left;">2.81</td>
<td style="text-align: left;">3.00</td>
<td style="text-align: left;">1.07</td>
</tr>
<tr class="even">
<td style="text-align: left;">When it comes to education, Jewish people tend to be overachievers</td>
<td style="text-align: left;">3.20</td>
<td style="text-align: left;">3.00</td>
<td style="text-align: left;">1.10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">On the whole, Jewish people are loyal to Israel</td>
<td style="text-align: left;">2.89</td>
<td style="text-align: left;">3.00</td>
<td style="text-align: left;">1.07</td>
</tr>
</tbody>
</table>
<div data-custom-style="table-note">
<p><em>Note.</em> Item scores are scored 1-6 (‘strongly disagree’ - strongly agree’)</p>
</div>
<p>&nbsp;</p>
</div>
</div>
</section>
</section>
<section id="pre-efa-tests" class="level1">
<h1>Pre-EFA Tests</h1>
<p>Next, we have to make sure that our data is suitable for factor analysis. We need to conduct two tests:</p>
<section id="kaiser-meyer-olkin-test" class="level2">
<h2 class="anchored" data-anchor-id="kaiser-meyer-olkin-test">Kaiser-Meyer-Olkin Test</h2>
<p>The Kaiser-Meyer-Olkin test (KMO) calculates a measure of sampling adequacy (MSA) for each item, and for your items overall. MSA less than 0.50 is really bad.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Is factor analysis is warranted?</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">KMO</span>(SASSEFA) <span class="co"># You should get rid of all variables with MSA &lt; 0.50, which we don't need to do here. </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Kaiser-Meyer-Olkin factor adequacy
Call: KMO(r = SASSEFA)
Overall MSA =  0.88
MSA for each item = 
                                Jewish.people.are.often.very.rude 
                                                             0.89 
                             Jewish.people.tend.to.complain.a.lot 
                                                             0.91 
            All.things.considered.Jewish.people.are.untrustworthy 
                                                             0.88 
                                      Jewish.people.can.be.sneaky 
                                                             0.89 
           When.they.feel.slighted.Jewish.people.will.be.vengeful 
                                                             0.92 
                         Jewish.people.tend.to.be.good.with.money 
                                                             0.76 
                        Jewish.people.tend.to.influence.the.media 
                                                             0.92 
When.it.comes.to.education.Jewish.people.tend.to.be.overachievers 
                                                             0.78 
                   On.the.whole.Jewish.people.are.loyal.to.Israel 
                                                             0.72 </code></pre>
</div>
</div>
<p>Overall KMO score is 0.88, which is quite good (above 0.90 is ideal, but 0.88 is pretty good).</p>
</section>
<section id="bartletts-test-of-sphericity" class="level2">
<h2 class="anchored" data-anchor-id="bartletts-test-of-sphericity">Bartlett’s Test of Sphericity</h2>
<p>Next, we do Bartlett’s test of sphericity, which is a linear algebra/matrix-related test we’re not going to get into here. Suffice it to say that Bartlett’s test evaluates whether the variables in our data are sufficiently correlated to proceed with factor analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cortest.bartlett</span>(SASSEFA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>R was not square, finding R from data</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$chisq
[1] 7051.592

$p.value
[1] 0

$df
[1] 36</code></pre>
</div>
</div>
<p>Fun fact, we can use the performance package to conduct both of these tests at once! The output even provides an explanatory example write-up!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">check_factorstructure</span>(SASSEFA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Is the data suitable for Factor Analysis?


  - Sphericity: Bartlett's test of sphericity suggests that there is sufficient significant correlation in the data for factor analysis (Chisq(36) = 7051.59, p &lt; .001).
  - KMO: The Kaiser, Meyer, Olkin (KMO) overall measure of sampling adequacy suggests that data seems appropriate for factor analysis (KMO = 0.88). The individual KMO scores are: Jewish.people.are.often.very.rude (0.89), Jewish.people.tend.to.complain.a.lot (0.91), All.things.considered.Jewish.people.are.untrustworthy (0.88), Jewish.people.can.be.sneaky (0.89), When.they.feel.slighted.Jewish.people.will.be.vengeful (0.92), Jewish.people.tend.to.be.good.with.money (0.76), Jewish.people.tend.to.influence.the.media (0.92), When.it.comes.to.education.Jewish.people.tend.to.be.overachievers (0.78), On.the.whole.Jewish.people.are.loyal.to.Israel (0.72).</code></pre>
</div>
</div>
</section>
</section>
<section id="number-of-factors" class="level1">
<h1>Number of Factors</h1>
<p>Next, we have to determine how many factors we should extract from our data. There are several methods to do this.</p>
<section id="kaiser-criterion-eigenvalues" class="level2">
<h2 class="anchored" data-anchor-id="kaiser-criterion-eigenvalues">Kaiser Criterion (Eigenvalues)</h2>
<p>According to Kaiser, if a factor has an Eigenvalue of 1 or higher, that factor should be retained.</p>
<p>“Eigenvalue” is another linear algebra term. It essentially tells you how data are spread out on a “line,” or in this case, an Eigenvector. Eigenvalues are scalar transformations applied to Eigenvectors, which themselves have magnitudes and directions (this will be important when we talk about rotation in a minute).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>ev <span class="ot">&lt;-</span> <span class="fu">eigen</span>(<span class="fu">cor</span>(SASSEFA)) <span class="co"># get Eigenvalues</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>ev<span class="sc">$</span>values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.0736669 1.5975626 0.7194669 0.5841090 0.4973981 0.4804799 0.4135245
[8] 0.3182940 0.3154982</code></pre>
</div>
</div>
<p>According to the output of the above code, the first two factors out of a potential 9 factors (i.e., one factor per variable, which would defeat the purpose of having factors) have Eigenvalues above one. This would suggest we retain two factors.</p>
<p>We can also get Eigenvalues from Scree plots, like the ones in the code chunk below. The second plot overlays parallel analysis, which used actual, simulated, and re-sampled data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">scree</span>(SASSEFA, <span class="at">pc=</span><span class="cn">FALSE</span>)  <span class="co"># Use pc=FALSE for factor analysis. "PC" refers to principal components analysis, which is beyond the scope of this tutorial (though it is related).</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fa.parallel</span>(SASSEFA, <span class="at">fa=</span><span class="st">"fa"</span>) <span class="co">#FA for Factor Analysis.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Parallel analysis suggests that the number of factors =  2  and the number of components =  NA </code></pre>
</div>
</div>
<p>In Scree plots, we’re looking for the “elbow” of the plot; that is, the inflection point after which each factor you add has Eigenvalues below 1. As the output helpfully tells us, this would suggest 2 factors.</p>
</section>
<section id="consensus-method" class="level2">
<h2 class="anchored" data-anchor-id="consensus-method">Consensus Method</h2>
<p>While Kaiser is arguable the most common method for determining the number of factors, there’s a neat function called n_factors which compares across multiple criteria for factor inclusion. Basically, it surveys multiple methods of choosing the number of factors you want, then gives you a sort of histogram to tell you how many methods encourage using each possible number of factors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Factor analysis is warranted. We must identify the appropriate number of factors. We set n_max at 9 because that's the largest number of factors we could have in this 9-item data set. </span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">n_factors</span>(SASSEFA, <span class="at">n_max =</span> <span class="dv">9</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>According to this plot, 2 factors seems to be the consensus among different methods. The dashed line represents the cumulative variance in the data explained by each number of factors you could extract. For 2 factors, we’re looking at just above 50% variance explained. Ideally, for factor analysis, we would prefer to see something closer to 70%.</p>
</section>
</section>
<section id="factor-loadings" class="level1">
<h1>Factor Loadings</h1>
<p>Now that we’ve settled on picking 2 factors, we have to figure out how well each variable “maps onto” each factor, which is called the “Factor loadings.” To do that, we need to choose what kind of rotation and what kind of factoring method (estimator) we want to use. Importantly, a variable can load onto multiple different factors at once, which is called “cross-loading.” Different rotation methods deal with cross-loading in different ways.</p>
<section id="rotation" class="level2">
<h2 class="anchored" data-anchor-id="rotation">Rotation</h2>
<p>“Rotation” has to do with how different the directions of vectors are. In our terms, it refers to how correlated or uncorrelated we think our factors should be.</p>
<p>If we assume our factors are entirely uncorrelated (i.e., independent), then we would use an orthogonal rotation to find our factor loadings.</p>
<section id="orthogonal-rotations" class="level3">
<h3 class="anchored" data-anchor-id="orthogonal-rotations">Orthogonal Rotations</h3>
<section id="varimax-rotation" class="level4">
<h4 class="anchored" data-anchor-id="varimax-rotation">Varimax Rotation</h4>
<p>Varimax rotation tries to reduce cross-loading and minimizes smaller loadings. This gives you clear, unambiguous factor structures.</p>
</section>
<section id="quartimax-rotation" class="level4">
<h4 class="anchored" data-anchor-id="quartimax-rotation">Quartimax Rotation</h4>
<p>Quartimax rotation tries to reduce the number of variables you need to comprise each factor. This makes interpretation simpler, but potentially at loss of some complexity.</p>
</section>
<section id="equamax-rotation" class="level4">
<h4 class="anchored" data-anchor-id="equamax-rotation">Equamax Rotation</h4>
<p>This is just a compromise between varimax and quartimax.</p>
<p>As an aside, orthogonality in 2D geometry is perpendicularity. So to understand orthogonality, think about two lines separated by a 90-degree angle, like an X- and Y-axis. No matter how far you travel along one axis, you don’t move at all along the other axis. These two axes, also called dimensions are thus independent, or not correlated. As we discussed, our factors are, in theory terms, a dimension. Furthermore, our factors can be expressed mathematically as vectors. Therefore, assuming an orthogonal factor structure, which orthogonal rotations do, would be to assume that one factor is uncorrelated with the other. If we drew the factors/vectors in 2D space, they would be perpendicular.</p>
</section>
</section>
<section id="oblique-rotation" class="level3">
<h3 class="anchored" data-anchor-id="oblique-rotation">Oblique Rotation</h3>
<p>Assuming orthogonality can be somewhat restrictive. It’s quite possible, depending on your theoretical question, that your factors will be correlated in some way. To capture this correlation, we can use oblique rotations.</p>
<section id="promax-rotation" class="level4">
<h4 class="anchored" data-anchor-id="promax-rotation">Promax Rotation</h4>
<p>Promax rotation is really good at structuring large data sets. However, it might lead to higher correlations between factors.</p>
</section>
<section id="oblimin-rotation" class="level4">
<h4 class="anchored" data-anchor-id="oblimin-rotation">Oblimin Rotation</h4>
<p>This approach can’t handle large data sets as well as promax; however, it often produces a simple, easier-to-interpret factor structure.</p>
<p>Which rotation method you choose depends a lot on your prior knowledge of the phenomena you’re studying. In our case, we are interested in stereotypes, which tend to be correlated. As such, we’ll use an oblique rotation. Past work has used oblimin rotation, so we will use that method here.</p>
</section>
</section>
</section>
<section id="factoring-method" class="level2">
<h2 class="anchored" data-anchor-id="factoring-method">Factoring Method</h2>
<p>We also have to specify our factoring method. Type “?fa” into R to find the documentation and a brief rationale for each “fm” (factoring method). The two best suited to our analysis here are fm=“pa,” which gives the <em>p</em>rincipal factor solution, and fm=“ml,” which gives the <em>m</em>aximum <em>l</em>ikelihood factor analysis.</p>
<p>Note how we include the rotation method and factoring method in the code below</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Oblimin Rotation; principal factor solution</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>SASS_efa_pa <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">fa</span>(SASSEFA, <span class="at">nfactors =</span> <span class="dv">2</span>, <span class="at">rotate=</span><span class="st">"oblimin"</span>, <span class="at">fm=</span><span class="st">"pa"</span>) <span class="sc">%&gt;%</span> <span class="fu">model_parameters</span>(<span class="at">sort =</span> <span class="cn">TRUE</span>, <span class="at">threshold =</span> <span class="st">"max"</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>SASS_efa_pa</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Rotated loadings from Factor Analysis (oblimin-rotation)

Variable                                                          |  PA1 |  PA2
-------------------------------------------------------------------------------
Jewish.people.are.often.very.rude                                 | 0.83 |     
Jewish.people.can.be.sneaky                                       | 0.82 |     
All.things.considered.Jewish.people.are.untrustworthy             | 0.80 |     
When.they.feel.slighted.Jewish.people.will.be.vengeful            | 0.73 |     
Jewish.people.tend.to.complain.a.lot                              | 0.72 |     
Jewish.people.tend.to.influence.the.media                         | 0.54 |     
Jewish.people.tend.to.be.good.with.money                          |      | 0.70
When.it.comes.to.education.Jewish.people.tend.to.be.overachievers |      | 0.57
On.the.whole.Jewish.people.are.loyal.to.Israel                    |      | 0.56

Variable                                                          | Complexity | Uniqueness
-------------------------------------------------------------------------------------------
Jewish.people.are.often.very.rude                                 |       1.01 |       0.33
Jewish.people.can.be.sneaky                                       |       1.00 |       0.32
All.things.considered.Jewish.people.are.untrustworthy             |       1.06 |       0.41
When.they.feel.slighted.Jewish.people.will.be.vengeful            |       1.04 |       0.41
Jewish.people.tend.to.complain.a.lot                              |       1.02 |       0.45
Jewish.people.tend.to.influence.the.media                         |       1.45 |       0.55
Jewish.people.tend.to.be.good.with.money                          |       1.01 |       0.48
When.it.comes.to.education.Jewish.people.tend.to.be.overachievers |       1.01 |       0.66
On.the.whole.Jewish.people.are.loyal.to.Israel                    |       1.04 |       0.71

The 2 latent factors (oblimin rotation) accounted for 51.97% of the total variance of the original data (PA1 = 37.71%, PA2 = 14.26%).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Oblimin Rotation; maximum likelihood solution</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>SASS_efa_ML <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">fa</span>(SASSEFA, <span class="at">nfactors =</span> <span class="dv">2</span>, <span class="at">rotate=</span><span class="st">"oblimin"</span>, <span class="at">fm=</span><span class="st">"ml"</span>) <span class="sc">%&gt;%</span> <span class="fu">model_parameters</span>(<span class="at">sort =</span> <span class="cn">TRUE</span>, <span class="at">threshold =</span> <span class="st">"max"</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>SASS_efa_ML</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Rotated loadings from Factor Analysis (oblimin-rotation)

Variable                                                          |  ML1 |  ML2
-------------------------------------------------------------------------------
Jewish.people.are.often.very.rude                                 | 0.83 |     
Jewish.people.can.be.sneaky                                       | 0.82 |     
All.things.considered.Jewish.people.are.untrustworthy             | 0.81 |     
When.they.feel.slighted.Jewish.people.will.be.vengeful            | 0.73 |     
Jewish.people.tend.to.complain.a.lot                              | 0.71 |     
Jewish.people.tend.to.influence.the.media                         | 0.54 |     
Jewish.people.tend.to.be.good.with.money                          |      | 0.70
When.it.comes.to.education.Jewish.people.tend.to.be.overachievers |      | 0.58
On.the.whole.Jewish.people.are.loyal.to.Israel                    |      | 0.56

Variable                                                          | Complexity | Uniqueness
-------------------------------------------------------------------------------------------
Jewish.people.are.often.very.rude                                 |       1.01 |       0.33
Jewish.people.can.be.sneaky                                       |       1.00 |       0.32
All.things.considered.Jewish.people.are.untrustworthy             |       1.07 |       0.40
When.they.feel.slighted.Jewish.people.will.be.vengeful            |       1.04 |       0.41
Jewish.people.tend.to.complain.a.lot                              |       1.02 |       0.45
Jewish.people.tend.to.influence.the.media                         |       1.43 |       0.56
Jewish.people.tend.to.be.good.with.money                          |       1.01 |       0.49
When.it.comes.to.education.Jewish.people.tend.to.be.overachievers |       1.00 |       0.66
On.the.whole.Jewish.people.are.loyal.to.Israel                    |       1.04 |       0.70

The 2 latent factors (oblimin rotation) accounted for 51.99% of the total variance of the original data (ML1 = 37.72%, ML2 = 14.27%).</code></pre>
</div>
</div>
<p>Columns PA1 and PA2 give you the factor loadings for each factor in the principal factor solution, while columns ML1 and ML2 give factor loadings for each variable in the maximum likelihood solution. The “threshold = MAX” argument hides cross-loadings for each variable on the other factor (i.e., the factor onto which they load less strongly).</p>
<p>Although the two solutions (PA and ML) reveal virtually no difference with out data, it’s good to be familiar with multiple factoring methods in EFA.</p>
<p>From the above output, we can see that 6 of our variables load onto the first factor, which explains roughly 38% of the variance. 3 variables load onto the second factor, which explains just over 14% of the variance. Cumulatively, our factors explain roughly 52% of the variance in our data (which is what we saw in the consensus methods plot above). 52% isn’t super high, but it’s a good start.</p>
<p>Looking at uniqueness, which refers to the proportion of variance for each variable that the factors explain, we see that the items on factor 2 tend to have higher uniqueness, meaning their variance is less well explained by our factors. The last item is particularly unique, despite it loading best onto factor 2.</p>
</section>
</section>
<section id="interpreting-factors" class="level1">
<h1>Interpreting Factors</h1>
<p>We now have an understanding of which variables map onto which factors. Let’s calculate internal consistency.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>Factor1 <span class="ot">&lt;-</span> SASSEFA <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="st">"Jewish.people.are.often.very.rude"</span>,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"Jewish.people.tend.to.complain.a.lot"</span>,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"All.things.considered.Jewish.people.are.untrustworthy"</span>,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Jewish.people.can.be.sneaky"</span>,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"When.they.feel.slighted.Jewish.people.will.be.vengeful"</span>,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Jewish.people.tend.to.influence.the.media"</span>)</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>Factor2 <span class="ot">&lt;-</span> SASSEFA <span class="sc">%&gt;%</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="st">"Jewish.people.tend.to.be.good.with.money"</span>,</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>         <span class="st">"When.it.comes.to.education.Jewish.people.tend.to.be.overachievers"</span>,</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>         <span class="st">"On.the.whole.Jewish.people.are.loyal.to.Israel"</span>)</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a><span class="fu">cronbach.alpha</span>(Factor1, <span class="at">standardized =</span> <span class="cn">TRUE</span>, <span class="at">CI =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Standardized Cronbach's alpha for the 'Factor1' data-set

Items: 6
Sample units: 1960
alpha: 0.887

Bootstrap 95% CI based on 1000 samples
 2.5% 97.5% 
0.875 0.896 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cronbach.alpha</span>(Factor2, <span class="at">standardized =</span> <span class="cn">TRUE</span>, <span class="at">CI =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Standardized Cronbach's alpha for the 'Factor2' data-set

Items: 3
Sample units: 1960
alpha: 0.635

Bootstrap 95% CI based on 1000 samples
 2.5% 97.5% 
0.601 0.669 </code></pre>
</div>
</div>
<p>Okay, Cronbach’s alpha for factor one is very good: 0.887! Cronbach’s alpha for our second factor, however, is a bit weaker at 0.635. So, what we may have here is one really clear factor (factor 1) plus some “extra stuff” that loosely goes together.</p>
<p>What we name these two factors (i.e., how we refer to them) really depends on preexisting theory. According to the stereotype content model (SCM), stereotype perceptions tend to fall along two dimensions; warmth (i.e., friendliness, morality), and competence (i.e., agency, ability; Fiske et al., 2007; Fiske, 2018). Factor 1 comprises stereotypes about Jewish people being antisocial: there are stereotypes about their tendencies to be rude, to complain, to seek revenge, and to deceive others. We can thus call factor 1 a “warmth” dimension. Factor 2 includes stereotypes about education, money, and global conspiracy (i.e., loyalty to a foreign power). so we’ll tentatively call this a “competence” dimension.</p>
<p>Now that we’ve done EFA, we’ll use another data set to test our hypothesis that these antisemitic stereotypes have an underlying 2-factor structure. See you in the next post, which will be on Confirmatory Factor Analysis!</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>